//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public Album()
        {
            this.Albums1 = new HashSet<Album>();
            this.Images = new HashSet<Image>();
        }
    
        public int AlbumId { get; set; }
        public int GalleryId { get; set; }
        public Nullable<int> ParentAlbumId { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Album> Albums1 { get; set; }
        public virtual Album Album1 { get; set; }
        public virtual Gallery Gallery { get; set; }
        public virtual ICollection<Image> Images { get; set; }
    }
}
