//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public Gallery()
        {
            this.Albums = new HashSet<Album>();
            this.Images = new HashSet<Image>();
        }
    
        public int GalleryId { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Album> Albums { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Image> Images { get; set; }
    }
}
