//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int UserId { get; set; }
        public string Username { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Gallery Gallery { get; set; }
    }
}
